### ISSUE TITLE
Script "repair.sh" missing on this repository

### ISSUE THREAD

**Issue by alexfernandes8a** [tzhu-bio/UMI-ATAC-seq#1]
Hi Tao Zhu,

Currently, I am using the UMI-ATAC-seq method described in the paper "ATAC-seq with unique molecular identifiers improves quantification and foot printing", published in 2020. Although, I realized that the "repair.sh" script  is missing.

Would you please make it available or guide me on how to get a similar result?

Your help is much appreciated! Thank you very much!

**Comment by alexfernandes8a** [comment]
Sorry! I just realized "repair.sh" is actually a function on BBMap that somehow is not on my Conda environment. Installing BBMap on my local env <as described here: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/installation-guide/> solved my issue.

**Comment by tzhu-bio** [comment]
Thank you for using our UMI-ATAC-seq method.  The **repair.sh** is a script from the bbmap package.  You can download the bbmap package and use the **repair.sh** script.
